### ISSUE TITLE
crash tracing to terser

### ISSUE THREAD

**Issue by GDBlaster** [mihai-vlc/uglifyjs-folder#36] opened 2022-12-22 23:08 UTC
when trying to minify a project I get this output
```ps1
> uglifyjs-folder.ps1 .\projectFolder -x .js -eo .\build
SyntaxError: 'return' outside of function
    at js_error (C:\Users\\AppData\Roaming\npm\node_modules\uglifyjs-folder\node_modules\terser\dist\bundle.min.js:554:11)
    at croak (C:\Users\\AppData\Roaming\npm\node_modules\uglifyjs-folder\node_modules\terser\dist\bundle.min.js:1278:9)
    at statement (C:\Users\\AppData\Roaming\npm\node_modules\uglifyjs-folder\node_modules\terser\dist\bundle.min.js:1481:21)
    at _embed_tokens_wrapper (C:\Users\\AppData\Roaming\npm\node_modules\uglifyjs-folder\node_modules\terser\dist\bundle.min.js:1343:26)
    at block_ (C:\Users\\AppData\Roaming\npm\node_modules\uglifyjs-folder\node_modules\terser\dist\bundle.min.js:2178:20)
    at statement (C:\Users\\AppData\Roaming\npm\node_modules\uglifyjs-folder\node_modules\terser\dist\bundle.min.js:1407:29)
    at _embed_tokens_wrapper (C:\Users\\AppData\Roaming\npm\node_modules\uglifyjs-folder\node_modules\terser\dist\bundle.min.js:1343:26)
    at if_ (C:\Users\\AppData\Roaming\npm\node_modules\uglifyjs-folder\node_modules\terser\dist\bundle.min.js:2161:44)
    at statement (C:\Users\\AppData\Roaming\npm\node_modules\uglifyjs-folder\node_modules\terser\dist\bundle.min.js:1477:24)
    at _embed_tokens_wrapper (C:\Users\\AppData\Roaming\npm\node_modules\uglifyjs-folder\node_modules\terser\dist\bundle.min.js:1343:26)
```

OS: windows 11
Term : Ms PowerShell

**Comment by ionutvmi** [comment] 2022-12-23 09:07
did you find any js files in your project that have this `SyntaxError: 'return' outside of function` ?

What is the contents of the `uglifyjs-folder.ps1` file ?

**Comment by GDBlaster** [comment] 2022-12-23 10:48
The .ps1 is an autogenerated powershell cmdlet either by yarn or npm when
installing

My code shouldnt contain any such error its running directly as a node
process (so not wrapped) any return outside of a function would cause a
crash on lauch

**Comment by ionutvmi** [comment] 2022-12-23 11:10
Maybe try to limit the number of files that you are minifying and see which specific file causes the error.

**Comment by GDBlaster** [comment] 2022-12-23 11:40
I will but I currently have a more urgent issue in the form of my buildx
not building for arm

**Comment by GDBlaster** [comment] 2022-12-29 17:05
I got back on trying to fix this but I'm not able to recreate the error however two of the files I am trying to merge require the same dependency under the same name such as:

## File1.js
```js
const fs = require("node:fs")

# code using fs
```

## File2.js
```js
const fs = require("node:fs")

# code using fs
```

the module throws an error "SyntaxError: 'fs' is redeclared"

this is an error i understand how to avoid but shouldn't the minifier deduplicate require statements?
this seems to be a weird limitation that might not be intended

**Comment by mihai-vlc** [comment] 2022-12-29 19:01
This is the intended behavior.

By default, the js files are minified for the browser where, are the top level, the variables are globals.

If you need to change this behavior you can have a look at the available configuration file options for terser: https://terser.org/docs/api-reference#minify-options


Normally, a server side nodejs application/module should not require bunding/minifcation.
If you you need to do it for some for some reason you can try to use `esbuild`.

If the original issue is resolved, please close this issue.

**Closed** 2022-12-29 19:31 UTC
